name: Continuous Integration
run-name: "${{ github.event_name == 'workflow_dispatch' && 'Manually' || 'Automatically' }} Triggered by ${{ github.actor }}"
on:  
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'snapshots/**'
      - 'analyses/**'

  pull_request:
    branches:
      - develop
      - stage
      - main
    types: 
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'docs/**'
      - 'snapshots/**'
      - 'analyses/**'

  workflow_dispatch:
    inputs:    
      full-refresh:
        description: wether to do a full refresh
        type: boolean
        required: false
        default: false
      
      models:
        description: comma separated model names or directories
        type: string
        required: false
        default: ''
jobs:
    prepare:
        runs-on: ubuntu-slim
        outputs:
          dbt-run-options: steps.prepare-options.outputs.options || ''
        
        steps:
          # - name: clone repository
          #   uses: actions/checkout@v6

          - name: prepare dbt run options
            id: prepare-options
            if: ${{ github.event_name == 'workflow_dispatch' }}
            run: echo "options=xhy" >> $GITHUB_OUTPUT
